version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - leximon-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - leximon-network

  leximon-api:
    image: leximon.api
    container_name: leximon-api
    build:
      context: .
      dockerfile: LexiMon.API/Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - TZ=Asia/Ho_Chi_Minh
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    depends_on:
      leximon-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - leximon-network

  leximon-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: leximon-db
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -lc '</dev/tcp/localhost/1433' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - leximon-network

volumes:
  sqlserverdata:

networks:
  leximon-network:
    driver: bridge