version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.8.0
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    labels:
      - com.github.nginx-proxy.nginx=false
    restart: unless-stopped
    networks:
      - leximon-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.6.0
    container_name: nginx-proxy-acme
    environment:
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - leximon-network

  leximon-api:
    image: leximon.api
    container_name: leximon-api
    build:
      context: .
      dockerfile: LexiMon.API/Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - TZ=Asia/Ho_Chi_Minh
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - VIRTUAL_PORT=8080
    depends_on:
      leximon-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - leximon-network

  leximon-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: leximon-db
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -lc '</dev/tcp/localhost/1433' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - leximon-network

volumes:
  sqlserverdata:

networks:
  leximon-network:
    driver: bridge